### ISSUE TITLE
Package not installing

### ISSUE THREAD

**Issue by alibaraneser** [vkosuri/django-dialogflow#7]
Hey,

When I install package, this error occur, What can I do?

```
(venv) aldebaran@aldebaran-Lenovo-IdeaPad-Y510P:~/PycharmProjects/dialogflow$ pip3 install django-dialogflow
Collecting django-dialogflow
  Using cached https://files.pythonhosted.org/packages/31/ab/42c0fc9e7687dfec5b6f46cc8cf952310317635bb0256c4ee627025e041c/django-dialogflow-0.0.3.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-0ob379ey/django-dialogflow/setup.py", line 19, in <module>
        with open('requirements.txt') as requirements:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-0ob379ey/django-dialogflow/

```

**Comment by vkosuri** [comment]
@alibaraneser I just published a new version to pypi, could you please try and let me know?
